site_name: ISIS1225 Notes
site_url: https://luigitoby.github.io/ISIS1225-notes/

nav:
  - Home: ISIS1225.md

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: lime
  features:
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - toc.follow
  extra_css:
    - docs/extra.css
