site_name: ISIS1225 Notes
site_url: https://luigitoby.github.io/ISIS1225-notes/

nav:
  - Home: ISIS1225.md

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: lime
  features:
    - navigation.instant
    - navigation.expand
    - toc.follow

plugins:
  - toc-nav:
      enabled: true
      toc_depth: 3   # include up to ### headings

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - extra.css
