site_name: ISIS1225 Notes
site_url: https://luigitoby.github.io/ISIS1225-notes/

nav:
  - Home: ISIS1225.md

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: lime
  features:
    - toc.integrate     # outline on the side
    - toc.follow        # outline scrolls with you
    - content.code.copy # copy button on code blocks

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
  - pymdownx.details     # collapsible sections
  - pymdownx.superfences
